#!/bin/bash

# Ref: https://github.com/chebro/dotfiles/blob/master/.config/notifications

POW=$(cat /sys/class/power_supply/BAT1/capacity)

if [ "$(cut -c 1 < /sys/class/power_supply/BAT0/status)" = D ] && [ "$POW" -lt 15 ]; then
    DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus dunstify -h string:x-canonical-private-synchronous:battery "Battery Status" "Running Low" -u CRITICAL
fi

