#!/usr/bin/env zsh

# Ref: https://github.com/chebro/dotfiles/blob/master/.config/notifications

CUR=$(echo $(cat /sys/class/backlight/*/brightness) / $(cat /sys/class/backlight/*/max_brightness) | bc -l)
BRI=$(echo $((CUR * 100)) | cut -d'.' -f1)

DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus dunstify -h string:x-canonical-private-synchronous:backlight "Brightness" -h int:value:"$BRI" -p -u LOW 1> /dev/null

