#!/usr/bin/env bash

## Author : Aditya Shakya (adi1090x)
## Mail : adi1090x@gmail.com
## Github : @adi1090x
## Reddit : @adi1090x

rofi_command="rofi -theme $HOME/.config/rofi-themes/powermenu.rasi"
uptime=$(uptime -p | sed -e 's/up //g')

# Options
shutdown="襤 Shutdown"
reboot=" Reboot"
lock=" Lock"
suspend="鈴 Suspend"
logout=" Logout"

# Variable passed to rofi
options="$shutdown\n$reboot\n$lock\n$suspend\n$logout"

chosen="$(echo -e "$options" | $rofi_command -p "Uptime - $uptime" -dmenu)"
case $chosen in
    $shutdown)
        systemctl poweroff
        ;;
    $reboot)
        systemctl reboot
        ;;
    $lock)
        betterlockscreen -l dim -t
        ;;
    $suspend)
        betterlockscreen -s dim -t
        ;;
    $logout)
        [[ "$MYWM" == "herbstluftwm" ]] && herbstclient quit
        [[ "$MYWM" == "i3wm" ]] && i3-msg exit
        [[ "$MYWM" == "bspwm" ]] && bspc quit
        ;;
esac
