#!/usr/bin/env bash

function printHelp()
{
    echo "Usage: armassemble [ASSEMBLY FILE]"
    exit 1
}

[[ $# != 1 ]] && printHelp

file=$(readlink -f "$1")

[[ $file =~ .*\.elf ]] && qemu-system-arm -M lm3s6965evb -cpu cortex-m3 -S -gdb tcp::1234 -nographic -kernel "$file" || echo "Input must be *.elf file"
