#!/usr/bin/env bash
WALL_DIR="$HOME/Pictures/wallpapers"

function printHelp()
{
cat << EOF
Usage:
    ${0##*/} [-h] [IMAGE]
    -h    Show this help and exit

    If no args are given, sets a random wallpaper from provided directory on
    each screen.
    If IMAGE is given, sets it as wallpaper (on all screens).
EOF
}

while getopts ":h" option; do
    case $option in
        h) printHelp; exit 0;;
        \?)
            echo "Invalid option"
            printHelp
            exit 1
            ;;
    esac
done
# Get all possible displays
screens_count=$(xrandr -q | grep "connected" | wc -l)
screens_count=$((screens_count-1))

nitrogen_command="nitrogen --set-auto"
for head in $(seq 0 $screens_count); do
    case "$#" in
        0) $nitrogen_command --random --head=$head "$WALL_DIR";;
        1) $nitrogen_command --head=$head $1;;
        *) printHelp; exit 1;;
    esac
done

echo "Set wallpaper(s)"
