#!/bin/bash

# Ref: https://github.com/chebro/dotfiles/blob/master/.config/notifications

# Invoked in udev rule: /etc/udev/rules.d/50-pluggedin.rules
# SUBSYSTEM=="power_supply", ENV{POWER_SUPPLY_STATUS}=="Charging", RUN+="~/.local/scripts/notif_unplugged"

DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus dunstify -h string:x-canonical-private-synchronous:battery "Battery Status" "Unplugged" -u LOW

