add_newline = true
format = """
$directory$git_branch$git_status$python
$status$character
"""

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"
vicmd_symbol = "[\\$](bold green)"

[git_branch]
symbol = " "
style = "bold green"

[git_status]
format = '([$all_status$ahead_behind]($style))'
conflicted = "=${count} "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
untracked = "?${count} "
stashed = "*${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "
style = "bold bright-green"

[python]
symbol = " "
detect_extensions = []

[status]
disabled = false
symbol = ""
